Split up getting started to simplified version and deep dive
taxprofiler/taxpasta pull request #95
Opened 2023-04-25 13:07 UTC by jfy133

* [x] fix #94 
* [x] description of feature/fix
* [ ] tests added/passed
* [x] add an entry to the [changelog](../CHANGELOG.md)

2023-04-25 13:07 UTC, jfy133 commented on CHANGELOG.md
> +-   Simplify getting started tutorial and move original to complex tutorial (#92)
```suggestion
-   Simplify getting started tutorial and move original to complex tutorial (#95)
```

2023-04-27 14:01 UTC, Midnighter requested changes
Couple of minor comments otherwise this looks good to me! Thank you for the quick action 🙂

2023-04-27 14:46 UTC, jfy133 commented on docs/tutorials/deepdive.md
(or rather moved the file and changed the intro

2023-04-27 19:25 UTC, Midnighter approved these changes

2023-04-28 06:38 UTC, merged